### ISSUE TITLE
Some data do not follow the BIDS standard

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/STOP-MS-data#3]
Eg:
~~~
sub-SMS008430_ses-20071213_ax_t1_3D_MPRAGE.nii.gz
~~~

The MPRAGE suffix is not authorized. See [documentation](https://bids-specification.readthedocs.io/en/stable/modality-specific-files/magnetic-resonance-imaging-data.html#anatomy-imaging-data)

**Comment by Mathilde-16** [comment]
Instead of the MPRAGE suffix, it should be the [UNIT1](https://github.com/sct-pipeline/STOP-MS-data/blob/ac8bfed1d01aacfd06eed9c8c2c6cff19948a7dc/scripts/process_data.sh#L52) suffix in order to respect BIDS convention, isn't it ?

(related to #2)

**Comment by jcohenadad** [comment]
> Instead of the MPRAGE suffix, it should be the [UNIT1](https://github.com/sct-pipeline/STOP-MS-data/blob/ac8bfed1d01aacfd06eed9c8c2c6cff19948a7dc/scripts/process_data.sh#L52) suffix in order to respect BIDS convention, isn't it ?

no it is not. Your images are clearly T1w MPRAGE contrast, not UNIT1 contrast:

<img width="565" alt="image" src="https://github.com/user-attachments/assets/bf92d93d-3450-44fb-bbdb-f7efa89cb7a4">

Moreover, the purpose of this issue is to report inconsistency with the data naming, not with the code. I suggest to 
- first, fix the data naming
- second, fix the code.

Not the other way around. 

I see that you've already committed the change in ac8bfed, but you will have to change it again once the data is properly named. 

I also suggest to open a PR that I will review, instead of pushing to the main branch directly at the risk of breaking the pipeline (it is currently broken as of ac8bfed because the data are named with suffix _MPRAGE).

**Comment by Mathilde-16** [comment]
Okay, thanks.

To fix the data naming, the `MP2RAGE` suffixe should be use. 
For example, the name of the subject below should be : `sub-SMS008430_ses-20071213_ax_t1_3D_MP2RAGE.nii.gz`
> sub-SMS008430_ses-20071213_ax_t1_3D_MPRAGE.nii.gz

Is it correct ?

**Comment by jcohenadad** [comment]
No it is not correct-- see my comment https://github.com/sct-pipeline/STOP-MS-data/issues/3#issue-2425691323. T1w is usually used for MPRAGE data.

Please use [BIDS validator](https://bids-standard.github.io/bids-validator/) to check the validity of your dataset

**Comment by Mathilde-16** [comment]
I've tried different ways to include "3D" and cor/ax/sag in the file name (eg : `desc` and `chunk` entities) but they didn't work (following the BIDS validator). 
So for now, the only solution I've found (validated by BIDS validator) is : `sub-SMS008430_ses-20071213_acq-mprage_T1w.nii.gz`

**Comment by jcohenadad** [comment]
sounds good-- please correct the dataset and then send me some representative data so I can continue improving/testing the code.

**Comment by Mathilde-16** [comment]
I apologise, I can't send you the dataset (or some representative subjects) due to the fact I don't have a KI adresse mail so I can't send them with a KI OneDrive link as Russell did last Thursday (when he send 11 subjects). And for security reasons, we have to use the KI OneDrive to share/send data. 

I can ask to Russell if he could correct the dataset following the BIDS standard and then send you back the 11 subjects

**Comment by Mathilde-16** [comment]
Hi again @jcohenadad, 
If you use the same link Russell shared you last week, you should normally have access to a second folder containing the files of 11 subjects following the BIDS convention.

**Comment by Mathilde-16** [comment]
> I've tried different ways to include "3D" and cor/ax/sag in the file name (eg : desc and chunk entities) but they didn't work (following the BIDS validator).

Is there any solution to keep information "3D" and cor/ax/sag in file names following the BIDS convention ? 

For my team, these are important details about each acquisitions. Indeed, the cohort includes 2D and 3D images, and coronal, axial and sagittal versions so it is quite variable since it is 15 years' worth of data over many different sessions.

**Comment by jcohenadad** [comment]
> Is there any solution to keep information "3D" and cor/ax/sag in file names following the BIDS convention ?

I would use the entity `acq-` for this. Eg:
- `acq-3dSag`
- `acq-2dAx`

**Comment by Mathilde-16** [comment]
Thank you very much. 

In order to add "mprage" detail, I've just tested with BIDS Validator tool some representative data with the entity `acq-` as below and it's working fine : 
- `acq-3dCorMprage`
- `acq-3dAxMprage`

Does this sound good for you too ?
