### ISSUE TITLE
Script comment about the PAM50 template

### ISSUE THREAD

**Issue by Mathilde-16** [sct-pipeline/STOP-MS-data#4]
I don't understand this [comment](https://github.com/sct-pipeline/STOP-MS-data/blob/755439d36eb87a69af28f297d05b1e5287a65b64/scripts/process_data.sh#L61) about the PAM50 template. As normalization requires the verte level file which we don't have, I should not add the `-normalize-PAM50` flag, isn't it ?

Could you explain me what this comment means please ?

**Comment by jcohenadad** [comment]
sorry-- comment was misleading-- removed it in e06ff0b
