### ISSUE TITLE
Manual PMJ labeling

### ISSUE THREAD

**Issue by Mathilde-16** [sct-pipeline/STOP-MS-data#7]
If I've understood correctly, it's necessary to go through all QCs for the `sct_detect_pmj` command only, I don't need to flag sessions for the `sct_deepseg` and `sct_process_segmentation` commands, isn't ?

**Comment by jcohenadad** [comment]
If the goal is to QC PMJ, then indeed, you only need to QC/correct the PMJ process.

If the goal is to QC the segmentation (which could also fail), then you also need to QC/correct the segmentation.

**Comment by Mathilde-16** [comment]
Okay I see, thank you !

**Comment by Mathilde-16** [comment]
My team has asked me to correct manually subjects who have a CSA below 40 mm2 or above 90mm2. I thought I'll correct these outlier values by doing the manual PMJ labeling. However, I've selected some subjects who have CSA below 40 or above 90mm2 and I've checked (thanks to the QC) if they correspond to subjects that have failed for the `sct_detect_pmj` command. But it's not the case, detection of the PMJ has worked well for these subjects so the `sct_detect_pmj` command didn't fail for them (this is the `sct_process_segmentation` command which failed). I thought outlier values (CSA) were due to a bad detection of the PMJ, but the failure comes from the `sct_process_segmentation` command.
Therefore, could you please explain if the manual PMJ labeling is supposed to correct outlier values of CSA ?

**Comment by jcohenadad** [comment]
check your segmentations

**Comment by Mathilde-16** [comment]
Thank you, now I can close this issue
